name: 'auto-commit'
 
on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/15 * * * *'
jobs:
  bot:
    runs-on: ubuntu-latest # 运行环境为最新版的Ubuntu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: fregante/setup-git-user@v1
        with:
          node-version: '14'
      - run: npm install -g yarn
      - run: yarn
      - run: yarn dev:node
      - run: git add api && git commit -m "update data" --no-verify
      - run: git pull
      - run: git push
